# Generated by Django 3.1.7 on 2021-04-09 16:57

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.IntegerField(help_text='line length in Meters')),
                ('diameter', models.FloatField(help_text='line diameter in Millimeters')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=crm.models.order_name, max_length=200, unique=True)),
                ('payed', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=crm.models.group_name, max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payed_sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UAH', 'Uah'), ('USD', 'Usd'), ('ERU', 'Eur')], default='UAH', max_length=3)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReducerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D3', models.FloatField()),
                ('D4', models.FloatField()),
                ('H2', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('line', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.line')),
            ],
        ),
        migrations.CreateModel(
            name='SpoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, default=10000, null=True)),
                ('D1', models.FloatField(default=1.0, help_text='Spool D1')),
                ('D2', models.FloatField()),
                ('H1', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.model')),
            ],
        ),
        migrations.CreateModel(
            name='SpoolModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_height', models.PositiveIntegerField(default=100)),
                ('img_width', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(blank=True, height_field='img_height', null=True, upload_to='spool_images', width_field='img_width')),
                ('spool_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.spoolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReducerModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_height', models.PositiveIntegerField(default=100)),
                ('img_width', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(blank=True, height_field='img_height', null=True, upload_to='reducer_images', width_field='img_width')),
                ('reducer_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.reducermodel')),
            ],
        ),
        migrations.AddField(
            model_name='reducermodel',
            name='spool_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.spoolmodel'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=2)),
                ('printed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.price')),
                ('reducer_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.reducermodel')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.ordergroup'),
        ),
        migrations.AddConstraint(
            model_name='reducermodel',
            constraint=models.UniqueConstraint(fields=('spool_model', 'line'), name='spool_line_const'),
        ),
    ]
